const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const url=process.env.APP_URL || 'http://localhost:4175';
const out=path.resolve(__dirname,'../reports');
const errors=[];
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 try {
  const context=await browser.newContext({viewport:{width:1440,height:1050}});
  const page=await context.newPage();
  page.on('pageerror',error=>errors.push(error.stack || error.message));
  page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
  await page.goto(url,{waitUntil:'networkidle'});
  await page.waitForFunction(()=>document.querySelectorAll('#featuredCrops .crop-card').length===4);
  await page.evaluate(async()=>{await navigator.serviceWorker.ready});
  await page.screenshot({path:path.join(out,'v5-desktop.png'),fullPage:true});
  assert(await page.locator('.brand').isVisible());
  await page.fill('#smartSearch','batata');
  await page.waitForFunction(()=>document.getElementById('smartSearchResults').textContent.includes('Solanum tuberosum'));
  await page.getByRole('button',{name:/CULTURA Batatinha Solanum tuberosum/}).click();
  await page.waitForFunction(()=>document.querySelector('#cultureResults details[open]'));
  assert.equal(await page.locator('#cultureResults .host-card').count(),1);
  await page.locator('#cultureResults .host-header button').click();
  await page.locator('.nav-btn[data-view=fieldView]').click();
  assert(await page.locator('#savedCrops').getByText('Solanum tuberosum').isVisible());
  await page.locator('.nav-btn[data-view=homeView]').click();
  await page.locator('#featuredCrops .crop-card').first().click();
  const photoCounts=await page.evaluate(()=>Object.fromEntries(DATABASE.hosts.find(h=>h.nome_cientifico==='Coffea arabica').patogenos.map(p=>[p.bacteria,app.findPhotosForBacteria(p.bacteria,'Coffea arabica').length])));
  assert.equal(photoCounts['Robbsia andropogonis'],0);assert.equal(photoCounts['Pseudomonas coronafaciens pv. garcae'],2);
  await page.locator('#cultureResults .photo-hint').first().click();
  await page.waitForFunction(()=>document.querySelectorAll('#photoGrid img').length>0 && [...document.querySelectorAll('#photoGrid img')].every(i=>i.complete && i.naturalWidth>0));
  await page.locator('#photoGrid .photo-card').first().click();
  await page.waitForFunction(()=>document.getElementById('photoViewerImg').naturalWidth>0);
  await page.keyboard.press('Escape');assert(await page.locator('#photoGalleryOverlay').isVisible());
  await page.keyboard.press('Escape');assert(!(await page.locator('#photoGalleryOverlay').isVisible()));
  await page.check('#compareModeToggle');
  await page.locator('.pathogen-checkbox').nth(0).check();await page.locator('.pathogen-checkbox').nth(1).check();
  await page.locator('#compareFab').click();
  await page.waitForFunction(()=>document.querySelectorAll('#pathogenMiniMap .leaflet-interactive').length>=27).catch(async error=>{console.log(JSON.stringify(await page.evaluate(()=>({html:document.getElementById('pathogenMiniMap').innerHTML.slice(0,1400),open:document.getElementById('pathogenMapOverlay').className,selection:app.selectedPathogens.size,features:app.boundaries?.features.length,count:document.querySelectorAll('#pathogenMiniMap .leaflet-interactive').length})),null,2));console.log(errors);throw error});
  await page.keyboard.press('Escape');
  await page.locator('.nav-btn[data-view=mapView]').click();
  await page.waitForFunction(()=>document.querySelectorAll('#map .leaflet-interactive').length===27).catch(async error=>{console.log(JSON.stringify(await page.evaluate(()=>({map:document.getElementById('map').innerHTML.slice(0,1000),count:document.querySelectorAll('#map .leaflet-interactive').length,initialized:app.mapInitialized})),null,2));console.log(errors);throw error});
  await page.selectOption('#mapState','RO');
  assert(await page.locator('#stateResultsTitle').textContent().then(t=>t.includes('Rondônia')));
  await page.screenshot({path:path.join(out,'v5-map-desktop.png'),fullPage:true});
  await page.locator('.nav-btn[data-view=diseaseView]').click();
  await page.fill('#diseaseSearch','garcae');
  await page.waitForFunction(()=>document.querySelectorAll('#diseaseResults .bacteria-row').length===1);
  await page.locator('#diseaseResults .bacteria-row>button').first().click();
  assert(await page.locator('#pathogenMapTitle').textContent().then(t=>t.includes('garcae')));
  await page.keyboard.press('Escape');
  await page.locator('.nav-btn[data-view=fieldView]').click();
  await page.locator('#downloadOffline').click();
  await page.waitForFunction(()=>document.getElementById('offlineProgress').value===275 && !document.getElementById('downloadOffline').disabled,{},{timeout:120000});
  // Check the downloaded photo collection, base records and local vector map without network.
  await page.evaluate(async()=>app.refreshOfflineStatus());
  await context.setOffline(true);await page.reload({waitUntil:'load'});
  await page.locator('.nav-btn[data-view=homeView]').click();
  await page.locator('#featuredCrops .crop-card').first().click();
  await page.locator('#cultureResults .photo-hint').first().click();
  await page.waitForFunction(()=>[...document.querySelectorAll('#photoGrid img')].every(i=>i.complete && i.naturalWidth>0));
  await page.keyboard.press('Escape');
  await page.locator('.nav-btn[data-view=mapView]').click();
  await page.waitForFunction(()=>document.querySelectorAll('#map .leaflet-interactive').length===27);
  await context.setOffline(false);
  for(const size of [{width:390,height:844},{width:360,height:740},{width:768,height:1024}]) {
   await page.setViewportSize(size); await page.locator('.nav-btn[data-view=homeView]').click();
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Home overflow ${size.width}`);
   await page.screenshot({path:path.join(out,`v5-home-${size.width}.png`),fullPage:true});
   await page.locator('#featuredCrops .crop-card').first().click();
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Culture overflow ${size.width}`);
   await page.screenshot({path:path.join(out,`v5-cafe-${size.width}.png`),fullPage:true});
   await page.locator('#cultureResults .map-hint').first().click();
   await page.waitForFunction(()=>document.querySelectorAll('#pathogenMiniMap .leaflet-interactive').length>=27);
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Modal overflow ${size.width}`);
   await page.screenshot({path:path.join(out,`v5-detail-${size.width}.png`),fullPage:false});
   await page.keyboard.press('Escape');
  }
  await page.locator('#themeToggle').click();
  await page.screenshot({path:path.join(out,'v5-dark.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'browser-check-v5.json'),JSON.stringify({passed:true,errors,photoCounts,checks:['search potato','direct culture entry','favorites','coffee photos','gallery and Escape','comparison map','27 states','RO filter','bacteria profiles','offline reload, photos and map','mobile widths 360/390/768','dark theme']},null,2));
  console.log('Browser checks passed. Screenshots and report: reports/');
 } finally {await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
